@startuml
class Mahasiswa {
    -id
    -name
    -function ()
}

class MataKuliah{
    -id
    -name
    -test()
}

class Testing{
    +fillable
    -fillable
    -function()
    -name()
}

Mahasiswa "*..1" - "*..*" MataKuliah
(Mahasiswa, Testing) . MataKuliah


@enduml