@startuml
package App{
    package model{
        class User{
            -name
            -email
        }
note right : pho artisan make:filament-resource UserResource --generate
}
package migration {
    class Create_User{
        -id
        -name
    }
note left : pho artisan make:filament-resource UserResource --generate
}
 package filament-resource {
    class UserResource{
        +test
    }
}
note right : pho artisan make:filament-resource UserResource --generate
}
@enduml